#!/usr/bin/python

# Constants
class Param:
	ZERO_PLANE_DIST = 120.0
	ZERO_PLANE_PIXEL_SIZE = 0.1052
	EMITTER_DCMOS_DISTANCE = 7.5
	MAX_SHIFT_VALUE = 2047
	MAX_DEPTH_VALUE = 10000.0
	CONST_SHIFT = 200.0
	PIXEL_SIZE_FACTOR = 1.0
	PARAM_COEFF = 4.0
	SHIFT_SCALE = 10.0
	DEPTH_MIN_CUTOFF = 0.0
	DEPTH_MAX_CUTOFF = 64434.0

lut = (Param.MAX_SHIFT_VALUE+10) * [0]

const_shift = Param.PARAM_COEFF * Param.CONST_SHIFT / Param.PIXEL_SIZE_FACTOR

plane_pixel_size = Param.ZERO_PLANE_PIXEL_SIZE * Param.PIXEL_SIZE_FACTOR
plane_dsr = Param.ZERO_PLANE_DIST

max_depth = min(Param.MAX_DEPTH_VALUE, Param.DEPTH_MAX_CUTOFF)

for shift in range(1, Param.MAX_SHIFT_VALUE):
	fixed_ref_x = (float(shift) - const_shift) / Param.PARAM_COEFF
	fixed_ref_x -= 0.375

	metric = fixed_ref_x * plane_pixel_size
	depth = Param.SHIFT_SCALE * ((metric * plane_dsr / (Param.EMITTER_DCMOS_DISTANCE - metric)) + plane_dsr)

	if depth > Param.DEPTH_MIN_CUTOFF and depth < max_depth:
		lut[shift] = depth

def gen_lines():
	for line in range(len(lut) / 5):
		sl = lut[line * 5:line * 5 + 5]
		yield "\t%s" % ', '.join([ '0x%04X' % val for val in sl ])

print "/* This file was autogenerated by generate_lut.py */"
print "static const __u16 depth_lut[] = {"
print ',\n'.join(list(gen_lines()))
print "};"
